apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mysql"
  namespace: "wordpress"
spec:
  # digitalocean
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
