apiVersion: apps/v1
kind: Deployment
metadata:
  name: "bukwp-kopfmysql"
  namespace: "wordpress"
  annotations:
    dpl: 0.1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kopfmysql-operator
  template:
    metadata:
      labels:
        app: kopfmysql-operator
    spec:
      serviceAccountName: "bukwp-kopfmysql-serviceaccount"
      containers:
        - name: kopfmysql-operator
          imagePullPolicy: Always
          image: quay.io/bukowwp/kopfmysql:wip
