name: python test

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: build
      run: make build
      working-directory: ./kopfmysql

    - name: run-ls
      run: make run-ls
      working-directory: ./kopfmysql

    - name: run mysql
      run: make run-mysql
      working-directory: ./kopfmysql

    - name: python
      run: make docker-test
      working-directory: ./kopfmysql
